ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      rvm use 2.4.4 --default
      bundle install --without production &&
      rails db:migrate
    command: >
      rails server
github:
    prebuilds:
        pullRequestsFromForks: true
